### ISSUE TITLE
Class Cast Exception

### ISSUE THREAD

**Issue by LolHens** [Zixiken/DimDoors#10]
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to com.zixiken.dimdoors.blocks.BlockDimDoorBase
	at com.zixiken.dimdoors.client.RenderDimDoor.renderTileEntityAt(RenderDimDoor.java:268)
	at com.zixiken.dimdoors.client.RenderDimDoor.func_180535_a(RenderDimDoor.java:27)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:168)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:141)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:992)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Zixiken** [comment]
I'm guessing it happened when you destroyed a dim door?

**Comment by LolHens** [comment]
Yes forgot to write that.
A creeper exploded.

**Comment by Zixiken** [comment]
Try with that change. I was able to chop down a field of dim doors without crashing XD
